name: Update Treasury Data
on:
  schedule:
    - cron: '0 4 * * *'  # Esegue alle 04:00 UTC (05:00 in Italia CET)
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.G_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install puppeteer axios dotenv
          npm install @solana/web3.js
          sudo apt-get update && sudo apt-get install -y jq

      # â¬‡ï¸ Esegui gli script e scrivi sia logs.json (strutturato) sia logs.txt (umano)
      - name: Run Scripts and write logs.json + logs.txt
        env:
          G_TOKEN: ${{ secrets.G_TOKEN }}
          HELIUS_API_KEY: ${{ secrets.HELIUS_API_KEY }}
          TENSOR_API_KEY: ${{ secrets.TENSOR_API_KEY }}
        shell: bash
        run: |
          set +e  # vogliamo sempre salvare i log anche se uno script fallisce
          START="$(date -u +%FT%TZ)"

          OUT1="$(node scripts/totalvalue.js 2>&1)"; RC1=$?
          OUT2="$(node scripts/calculate.js 2>&1)"; RC2=$?

          END="$(date -u +%FT%TZ)"
          OK="false"; if [ "$RC1" -eq 0 ] && [ "$RC2" -eq 0 ]; then OK="true"; fi

          # --- LOG TESTUALE (legibile a schermo) ---
          RAW_TEXT="=== Update Treasury Data ===
Started at: $START

----- totalvalue.js -----
$OUT1

----- calculate.js -----
$OUT2

Finished at: $END
Status: $OK"

          # (opzionale) maschera eventuali segreti se mai finissero nei log
          RAW_TEXT_MASKED="$(printf "%s" "$RAW_TEXT" \
            | sed -E 's/([A-Za-z0-9_]*API[_A-Za-z0-9]*=)?[A-Za-z0-9]{24,}/[REDACTED]/g')"

          # Scrivi logs.txt (root) e copia storica
          printf "%s\n" "$RAW_TEXT_MASKED" > logs.txt
          TS_SAFE="${START//:/-}"
          mkdir -p logs
          cp logs.txt "logs/${TS_SAFE}_run-${GITHUB_RUN_ID}.txt"

          # --- LOG JSON STRUTTURATO (per la tua pagina/JS) ---
          jq -n \
            --arg runId "${GITHUB_RUN_ID}" \
            --arg startedAt "$START" \
            --arg finishedAt "$END" \
            --arg ok "$OK" \
            --arg out1 "$OUT1" --argjson rc1 "$RC1" \
            --arg out2 "$OUT2" --argjson rc2 "$RC2" \
            --arg raw "$RAW_TEXT_MASKED" \
            '{
              runId: ($runId|tonumber),
              startedAt: $startedAt,
              finishedAt: $finishedAt,
              ok: ($ok=="true"),
              steps: [
                { name: "totalvalue.js", exitCode: $rc1, output: $out1 },
                { name: "calculate.js", exitCode: $rc2, output: $out2 }
              ],
              raw: $raw
            }' > logs.json

          # Copia storica JSON (opzionale)
          cp logs.json "logs/${TS_SAFE}_run-${GITHUB_RUN_ID}.json"

          echo "ðŸ“„ logs.txt e logs.json creati."

      - name: Check file changes
        run: |
          echo "ðŸ“‚ Anteprima logs.txt:"
          head -n 50 logs.txt || true
          echo ""
          echo "ðŸ“‚ Anteprima logs.json:"
          head -c 1000 logs.json || true
          echo ""
          echo "ðŸ“‚ Git status:"
          git status
        continue-on-error: true

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json logs.json logs.txt logs
          git commit -m "ðŸ”„ Aggiornamento tesoreria + logs.json + logs.txt" || echo "Nessun cambiamento da committare"
          git push origin main
